### ISSUE TITLE
Double left click

### ISSUE THREAD

**Issue by rayman89** [webextensions/close-tab-by-double-right-click#1]
Hello I saw that you replied a way to modify your addon to double left click and I was interested but I noticed your addon does close the tab when right clicking on the page area and was wondering if it would be possible to make it only work when left clicking or right clicking over the tab area only. Would that be possible to make? (sorry I don't know much about coding).

**Comment by webextensions** [comment]
Hi

Since you are asking about double left clicking on the tab header itself:
**Apparently, that is not supported in the new WebExtensions architecture used by Firefox.**

In some of the comments in Firefox extension review page, it was not clear that whether the users were referring to double-left-clicking on the page or on the tab-header :-)

I understand that you might be used to double-left-click-on-tab-header for easily closing the tab via some old browser extensions.

**But, in short, let me try to convey why I like the approach of this extension better than the approach used by some of those old browser extensions.**

Assumptions:
- I prefer using mouse over keyboard
- I work with many tabs which I keep on opening/closing every now and then
- Now, I am reading/scrolling through a page and I wish to close it.
- My mouse is already somewhere in the page

**With other extensions**, if I wish to close the tab by double-clicking on the tab header, I would need to do 4 small operations:
1. Look at my mouse position
2. Look at the current tab's position
3. Move the mouse to the tab header
4. Double click on tab header to close it

**With this extension**, if I wish to close the tab by double-right-clicking anywhere in the page, I would need to do 1 small operation:
1. Double right click wherever my mouse is
That's it ... Saves around 100ms to 500ms every time I close the tab ;-)

**Sidenote:**
There is a bug for Firefox-on-Windows due to which the context menu remains open even after a tab is closed using this extension. I'll file a bug report to Firefox regarding that.

Closing this issue.

**Comment by rayman89** [comment]
Thanks for your response.
