### ISSUE TITLE
Unspecified Rocker gesture along with double-right-click

### ISSUE THREAD

**Issue by tasic99** [webextensions/close-tab-by-double-right-click#17]
after extension update
https://github.com/webextensions/close-tab-by-double-right-click/issues/16#issue-2751746761
not only  double-right-click closes tab but mouse rocker gesture (leftclick-rightclick) does tab close 
this is a little bit confusing
can you please remove  rocker gesture

**Comment by webextensions** [comment]
@tasic99
Thank you for this report :+1: 

The issue was happening because of changes done for https://github.com/webextensions/close-tab-by-double-right-click/issues/12 which was done to add an alternate gesture for the Firefox users because of a browser bug. Apparently, in the recent versions of Firefox, the bug has been fixed so the alternate gesture isn't needed anymore.

With the fix, the version `2.2.0` of the extension is now available at the Chrome Web Store and it should work as expected.
