### ISSUE TITLE
Conflicts with right click menu on Unix/Linux

### ISSUE THREAD

**Issue by Avispa** [webextensions/close-tab-by-double-right-click#3]
Issue seems to be known. The plugin *Opera Gestures* for *Firefox* has a special setting for *Unix* in this regard.

Check https://github.com/ys0115/OperaGestures.

**Comment by webextensions** [comment]
@Avispa 
Are you talking about the case when the user did double-right-click and effectively closed the tab, but the right click menu remains open?
That is a bug in Firefox browser. In Chrome, that works fine.

Are you talking about the case that the right click menu opens up for the first right click?
Not stopping the first right click is deliberate, because doing that would only slow down the genuine use-case of a single-right-click only operation.

If you are talking about something else, kindly elaborate.

**Comment by Avispa** [comment]
Even worse, there will be no right click menu at all.

Considering a double click as a series of button "down, up, down,up" the tab closes on the first button up. No menu ever displayed. If the Action is performed slow with a long break between down+up, nothing will happen at all.

**Comment by webextensions** [comment]
Potentially fixed with some other updates or with a behavioral change as described in https://github.com/webextensions/close-tab-by-double-right-click/issues/12
